# Generated by Django 3.0.8 on 2020-11-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_favorite_favoriteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imgsrc',
            field=models.ImageField(default='', upload_to='static/images/products'),
        ),
    ]
