# Generated by Django 3.0.8 on 2020-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201010_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='destination',
        ),
        migrations.AddField(
            model_name='product',
            name='destination',
            field=models.ManyToManyField(to='products.Destination'),
        ),
    ]
