# Generated by Django 3.0.8 on 2020-10-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_attr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attr',
            new_name='attributes',
        ),
    ]
