# Generated by Django 3.1.3 on 2020-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201106_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
