# Generated by Django 3.1.3 on 2020-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201109_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeitem',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
