# Generated by Django 3.1.3 on 2020-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_imgsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgsrc',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/products'),
        ),
    ]
